/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SiddhiVinayaka' at '2/6/17 2:21 PM' with Gradle 3.0
 *
 * @author SiddhiVinayaka, @date 2/6/17 2:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
