import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'SiddhiVinayaka' at '2/6/17 2:21 PM' with Gradle 3.0
 *
 * @author SiddhiVinayaka, @date 2/6/17 2:21 PM
 */

//Org IVAVSYS
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
